version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/source/conf.py

 formats:
    - pdf
    - epub

python:
  version: 3.7
  install:
    - requirements: requirements.txt
    - method: pip
      path: .